sources:
  - name: BBC News
    country: International
    rss_url: https://feeds.bbci.co.uk/news/world/rss.xml
  - name: Reuters World
    country: International
    rss_url: https://www.reutersagency.com/feed/?best-topics=world&post_type=best
  - name: Hespress
    country: Maroc
    rss_url: https://fr.hespress.com/feed
  - name: France24
    country: France
    rss_url: https://www.france24.com/fr/rss
